server:
  servlet:
    context-path: /otpmobile/ticketing/core
  port: 4000
  
spring:
  application:
    name: core
  task:
    execution.thread-name-prefix: ${spring.application.name}-
  jpa:
    hibernate.ddl-auto: none
  datasource:
    hikari:
      pool-name: SpringBootJPAHikariCP
      connection-timeout: 5000
      maximum-pool-size: 10
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=ORACLE
    username: SA
    password:
  h2:
    console.enabled: true
